### ISSUE TITLE
CloudFormation stack creation failure - Failed to create "CodeBuildWaitCondition"

### ISSUE THREAD

**Issue by ori-scala** [aws-solutions-library-samples/aws-batch-arch-for-protein-folding#41]
Got this error when creating the container stack:
```
Embedded stack arn:aws:cloudformation:us-east-1:XXX:stack/alphafold-by-aws-batch-Container-1KFI9EKUZW572/63f4e690-394b-11f0-a693-0affe95ac3a5 was not successfully created: The following resource(s) failed to create: [CodeBuildWaitCondition].
```

**Comment by brianloyal** [comment]
Fixed with #42

**Comment by ori-scala** [comment]
@brianloyal Unfortunately, I still experience the same issue. This is what I see in the nested stack  for codebuild
```
WaitCondition timed out. Received 0 conditions when expecting 1
``` 

This is on the main one:
```
Embedded stack arn:aws:cloudformation:us-east-1:XXX:stack/alphafold-by-aws-batch-Container-1TGMV2RJTPT63/a47fc310-3bf8-11f0-8826-0e7e12f9f75f was not successfully created: The following resource(s) failed to create: [CodeBuildWaitCondition].
```
